-- 7 column grid
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "right", function ()
    hs.grid.setGrid("7x1").resizeWindowThinner().resizeWindowWider().pushWindowRight()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "left", function ()
    hs.grid.setGrid("7x1").resizeWindowThinner().resizeWindowWider().pushWindowLeft()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "up", function ()
    hs.grid.setGrid("7x1").resizeWindowWider()
end)
hs.hotkey.bind({"ctrl", "alt", "cmd"}, "down", function ()
    hs.grid.setGrid("7x1").resizeWindowThinner()
end)

-- 3 column grid
hs.hotkey.bind({"ctrl", "alt"}, "right", function ()
    hs.grid.setGrid("3x1").pushWindowRight()
end)
hs.hotkey.bind({"ctrl", "alt"}, "left", function ()
    hs.grid.setGrid("3x1").pushWindowLeft()
end)
hs.hotkey.bind({"ctrl", "alt"}, "up", function ()
    hs.grid.setGrid("3x1").resizeWindowWider()
end)
hs.hotkey.bind({"ctrl", "alt"}, "down", function ()
    hs.grid.setGrid("3x1").resizeWindowThinner()
end)
